export const measurements = {
  maleTop: {
    length: "Length",
    shoulder: "Shoulder",
    longSleeve: "Long Sleeve",
    collar: "Collar",
    chest: "Chest",
    cuff: "Cuff",
    sit: "Sit",
    stomach: "Stomach",
  },
  maleBottom: {
    length: "Length",
    shoulder: "Shoulder",
    longSleeve: "Long Sleeve",
    collar: "Collar",
    chest: "Chest",
    cuff: "Cuff",
    sit: "Sit",
    stomach: "Stomach",
  },

  pant: {
    waist: "Waist",
    sit: "Sit",
    knee: "Knee",
    length: "Length",
    opening: "Opening",
    thigh: "Thigh",
    hip: "Hip",
  },
  shirt: {
    length: "Length",
    shoulder: "Shoulder",
    longSleeve: "Long Sleeve",
    collar: "Collar",
    chest: "Chest",
    cuff: "Cuff",
    sit: "Sit",
    stomach: "Stomach",
  },
  suit: {
    length: "Length",
    shoulder: "Shoulder",
    longSleeve: "Long Sleeve",
    collar: "Collar",
    chest: "Chest",
    stomach: "Stomach",
    sit: "Sit",
  },
};
