import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Measure Mate",
  description: "Generated by create next app",
};
``;
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-10/12 md:w-3/4 lg:w-2/4 flex flex-col m-auto items-center  rounded-md">
          <Toaster richColors />
          {children}
        </div>
      </body>
    </html>
  );
}
